[dependencies]
cgal = "*"
mesalib = "*"
libglu = "*"
libopengl = "*"
xorg-libxi = "*"
libxkbcommon = "*"


[pypi-dependencies]
numpy = "*"
trimesh = { version = "*", extras = ["easy"] }
pymeshlab = "*"